export enum Role {
  ADMIN = "ADMIN",
  USER = "USER",
}
export const DB = {
  users: [
    {
      id: "1",
      name: "Alla",
      email: "alla@email.com",
      role: Role.ADMIN,
      cvIds: ["1"],
    },
    {
      id: "2",
      name: "Aya",
      email: "aya@email.com",
      role: Role.USER,
      cvIds: ["2"],
    },
    {
      id: "3",
      name: "Oumayma",
      email: "oumayma@email.com",
      role: Role.USER,
      cvIds: ["3"],
    },
    {
      id: "4",
      name: "Ghayda",
      email: "ghayda@email.com",
      role: Role.ADMIN,
      cvIds: ["4"],
    },
    {
      id: "5",
      name: "Chaima",
      email: "chaima@email.com",
      role: Role.USER,
      cvIds: ["5"],
    },
    {
      id: "6",
      name: "Salah",
      email: "salah@email.com",
      role: Role.USER,
      cvIds: ["6"],
    },
    {
      id: "7",
      name: "Foulen",
      email: "foulen@email.com",
      role: Role.USER,
      cvIds: ["7"],
    },
    {
      id: "8",
      name: "Falten",
      email: "falten@email.com",
      role: Role.ADMIN,
      cvIds: ["8"],
    },
  ],

  skills: [
    { id: "1", designation: "JavaScript", cvIds: ["1", "2", "5"] },
    { id: "2", designation: "TypeScript", cvIds: ["1", "3", "6"] },
    { id: "3", designation: "GraphQL", cvIds: ["2", "4", "7"] },
    { id: "4", designation: "React", cvIds: ["3", "5", "8"] },
    { id: "5", designation: "Node.js", cvIds: ["4", "6", "8"] },
    { id: "6", designation: "CSS", cvIds: ["1", "7", "8"] },
  ],

  cvs: [
    {
      id: "1",
      name: "CV Alla",
      age: 25,
      job: "Frontend Developer",
      skillIds: ["1", "2", "6"],
      cvOwnerId: "1",
    },
    {
      id: "2",
      name: "CV Aya",
      age: 28,
      job: "Fullstack Developer",
      skillIds: ["1", "3"],
      cvOwnerId: "2",
    },
    {
      id: "3",
      name: "CV Oumayma",
      age: 23,
      job: "UI Designer",
      skillIds: ["2", "4"],
      cvOwnerId: "3",
    },
    {
      id: "4",
      name: "CV Ghayda",
      age: 30,
      job: "Backend Developer",
      skillIds: ["3", "5"],
      cvOwnerId: "4",
    },
    {
      id: "5",
      name: "CV Chaima",
      age: 27,
      job: "React Developer",
      skillIds: ["1", "4"],
      cvOwnerId: "5",
    },
    {
      id: "6",
      name: "CV Salah",
      age: 32,
      job: "DevOps Engineer",
      skillIds: ["2", "5"],
      cvOwnerId: "6",
    },
    {
      id: "7",
      name: "CV Foulen",
      age: 26,
      job: "GraphQL Specialist",
      skillIds: ["3", "6"],
      cvOwnerId: "7",
    },
    {
      id: "8",
      name: "CV Falten",
      age: 29,
      job: "Software Architect",
      skillIds: ["4", "5", "6"],
      cvOwnerId: "8",
    },
  ],
};
